language: ruby
cache: bundler
rvm:
- 2.3.0
services:
- redis-server
- rabbitmq
script:
- bundle exec rspec
env:
  global:
    secure: Vwv8eJ9gU3iOAmRMUW5PEWm1PvzyH8Ph1FQzfnY4iPD4LEQH39wL+3gEw3iyp2QU/Toi3JFdm/nKRt2VM59MPLIqUgs9zjN7g+NLPrMDNjPdTq+Gz3d1x8OPtBu5C5DSmsxy+OPnhwG+q0Qf57tOypbsOXz9oJ49ajoRNaxwaHI=
